[DEFAULT]

# (STR) CSV dataset file path
csv_path = "data/dataset.csv"

# --- Controller params ---

# (INT) Target switch DPID for logging traffic information
target_dpid = 3

# (INT) Time interval between monitoring (in seconds)
interval = 1

# --- Model params ---

# (STR) Path where the trained model will be saved
model_path = "models/traffic_model.keras"

# (INT) Training epochs
epochs = 200

# (INT) Training batch size
batch_size = 32

# (INT) Sequence length for LSTM
sequence_length = 15

# (FLOAT) Training/validation slice
training_slice = 0.8